### ISSUE TITLE
Filter out suggestions that have position of -1

### ISSUE THREAD

**Issue by richiemccoll** [nearform/reviewbot#22]
Some diffs end up with a position of -1. This causes validation response errors (status code 422) from Github when posting the review.

This implies that the function that determines where the file is in relation to the Git hunk has potentially incorrect logic. We need to filter out any suggestions [here](https://github.com/nearform/reviewbot/blob/main/services/webhookApp.js#L87) and log them in the GCP console, this way we can debug further and write [unit tests](https://github.com/nearform/reviewbot/blob/main/tests/utils.test.js#L16) to isolate and fix.

**Comment by nherment** [comment]
This has been implemented and the diff location have been fixed by using a third party lib.
